name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - run: |
        mkdir pathupload
        echo "artifactPath=pathupload/file.txt" >> $GITHUB_ENV
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: myartifact
        path: ${{ env.artifactPath }}
        retention-days: 5
      
