name: Bump versions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@master
      - name: Build docker file
        run: docker build -t mypyimage .
