name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # first action check out:source code
      - name: Build the docker image
        run: docker build -t  --file Dockerfile --tag mypyromoimage
